services:
  db:
    container_name: pg
    image: postgres:15.0
    environment:
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
    expose:
      - 5432
  web:
    depends_on:
      - db
    build: .
    ports:
      - "127.0.0.1:3000:3000"
