name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Do Server Job
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ -d game ]; then cd game && git pull git@github.com:tbilisi-student-team/game.git;
            else git clone git@github.com:tbilisi-student-team/game.git && cd game; fi
            
            docker stop pew-game
            docker build --tag pew-game-image .
            docker run --name pew-game -p 127.0.0.1:3000:3000 -d pew-game-image
